//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courswork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceID { get; set; }
        public int ScheduleID { get; set; }
        public int ChildID { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    
        public virtual Children Children { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
